create table public.emergency_contacts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 80),
  phone_e164 text not null check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  channel text not null default 'sms' check (channel in ('sms')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, phone_e164)
);

create index emergency_contacts_user_id_idx
  on public.emergency_contacts (user_id);

comment on table public.emergency_contacts is
  'Contactos responsables del usuario para avisos automaticos de emergencia.';

alter table public.emergency_contacts enable row level security;

create policy emergency_contacts_read_own
on public.emergency_contacts for select to authenticated
using ((select private.is_vitalwatch_user(user_id)));

create policy emergency_contacts_insert_own
on public.emergency_contacts for insert to authenticated
with check ((select private.is_vitalwatch_user(user_id)));

create policy emergency_contacts_update_own
on public.emergency_contacts for update to authenticated
using ((select private.is_vitalwatch_user(user_id)))
with check ((select private.is_vitalwatch_user(user_id)));

create policy emergency_contacts_delete_own
on public.emergency_contacts for delete to authenticated
using ((select private.is_vitalwatch_user(user_id)));

revoke all on table public.emergency_contacts from anon;
grant select, insert, update, delete on table public.emergency_contacts to authenticated;
grant all on table public.emergency_contacts to service_role;
grant usage, select on sequence public.emergency_contacts_id_seq to authenticated, service_role;

create table public.emergency_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.device_events(id) on delete cascade,
  contact_id bigint not null references public.emergency_contacts(id) on delete cascade,
  channel text not null check (channel in ('sms')),
  status text not null check (status in ('queued', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, contact_id, channel)
);

create index emergency_deliveries_event_id_idx
  on public.emergency_deliveries (event_id);

create index emergency_deliveries_contact_id_idx
  on public.emergency_deliveries (contact_id);

comment on table public.emergency_deliveries is
  'Registro idempotente de cada aviso de emergencia enviado por un proveedor externo.';

alter table public.emergency_deliveries enable row level security;

create policy emergency_deliveries_read_own
on public.emergency_deliveries for select to authenticated
using (
  exists (
    select 1
    from public.emergency_contacts contact
    where contact.id = emergency_deliveries.contact_id
      and (select private.is_vitalwatch_user(contact.user_id))
  )
);

revoke all on table public.emergency_deliveries from anon;
grant select on table public.emergency_deliveries to authenticated;
grant all on table public.emergency_deliveries to service_role;
grant usage, select on sequence public.emergency_deliveries_id_seq to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'emergency_contacts'
  ) then
    alter publication supabase_realtime add table public.emergency_contacts;
  end if;
end
$$;
